#!/usr/bin/env bash
set -euo pipefail

# Render the whole Homebrew formula for VERSION into FORMULA, which lives in the
# abbyssoul/homebrew-abyss tap. The formula is generated: this template, not the
# tap copy, is the source, and the next release overwrites any hand edit there.
#
# Every platform installs a release archive built and checksummed by the release
# workflow, so no Homebrew user needs a Rust toolchain: macOS archives are native
# builds, Linux archives are static musl builds that run on any distribution.

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/release/lib.sh
source "$script_dir/lib.sh"

if [[ $# -ne 6 ]]; then
    echo "usage: $0 FORMULA VERSION MACOS_ARM64_SHA MACOS_INTEL_SHA LINUX_ARM64_SHA LINUX_X86_64_SHA" >&2
    exit 2
fi

formula="$1"
version="$2"
macos_arm64_sha="$3"
macos_intel_sha="$4"
linux_arm64_sha="$5"
linux_x86_64_sha="$6"

release_validate_version "$version"
for checksum in "$macos_arm64_sha" "$macos_intel_sha" "$linux_arm64_sha" "$linux_x86_64_sha"; do
    if [[ ! "$checksum" =~ ^[a-f0-9]{64}$ ]]; then
        release_error "invalid SHA-256: $checksum"
        exit 1
    fi
done

# The same release may be rendered again (a rerun is a no-op); an older one may
# never replace a newer formula. Every formula this tap has carried names its
# release in a /releases/download/vX.Y.Z/ URL.
if [[ -e "$formula" ]]; then
    mapfile -t current < <(
        grep -Eo '/releases/download/v[0-9]+\.[0-9]+\.[0-9]+/' "$formula" |
            sed -E 's|/releases/download/v([^/]+)/|\1|' | sort -u
    )
    if [[ "${#current[@]}" -ne 1 ]]; then
        release_error "cannot read one current release from $formula (found ${#current[@]})"
        exit 1
    fi
    if [[ "${current[0]}" != "$version" ]]; then
        release_require_newer "$version" "${current[0]}"
    fi
fi

base="https://github.com/abbyssoul/kinjo/releases/download/v${version}/kinjo-${version}"
rendered="$(mktemp)"
trap 'rm -f "$rendered"' EXIT

cat > "$rendered" <<EOF
# Generated by https://github.com/abbyssoul/kinjo/blob/main/scripts/release/update-homebrew-formula.sh
# for each release. Edit the template there: the next release overwrites
# changes made here.
class Kinjo < Formula
  desc "TUI and command launcher for local network mDNS services"
  homepage "https://github.com/abbyssoul/kinjo"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}-aarch64-apple-darwin.tar.gz"
      sha256 "${macos_arm64_sha}"
    end

    on_intel do
      url "${base}-x86_64-apple-darwin.tar.gz"
      sha256 "${macos_intel_sha}"
    end
  end

  on_linux do
    on_arm do
      url "${base}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${linux_arm64_sha}"
    end

    on_intel do
      url "${base}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${linux_x86_64_sha}"
    end
  end

  # kinjo discovers commands in \`share/kinjo/commands\` relative to its own
  # binary, so installing into pkgshare/"commands" makes the bundled defaults
  # work out of the box — no post-install copying.
  def install
    bin.install "kinjo"
    (pkgshare/"commands").install Dir["commands/*.toml"]
  end

  def caveats
    <<~EOS
      Default command definitions were installed to:
        #{opt_pkgshare}/commands

      kinjo discovers them there automatically. To customize a command, copy
      it to ~/.config/kinjo/commands (or \$XDG_CONFIG_HOME/kinjo/commands) and
      edit it; a user command with the same name overrides the bundled one.
    EOS
  end

  test do
    # \`ssh\` is one of the bundled defaults; seeing it proves the binary
    # discovered the commands installed under pkgshare.
    assert_match "ssh", shell_output("#{bin}/kinjo list-commands")
  end
end
EOF

mkdir -p "$(dirname "$formula")"
cp "$rendered" "$formula"
