name: Publish Crate package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6

      - name: Check Cargo.toml version matches release tag
        run: test "v$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" = "${{ github.ref_name }}"

      - name: Publish Crate
        run: cargo publish --locked --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
